# Generated by Django 4.2.7 on 2025-03-28 17:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_do_filme', models.CharField(max_length=100)),
                ('ano_lancamento', models.IntegerField()),
                ('estudio', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=50)),
                ('sinopse', models.TextField()),
                ('data_de_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50)),
                ('data_de_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
