# Generated by Django 4.2.7 on 2025-03-28 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_filme_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genero',
            old_name='genero',
            new_name='nome',
        ),
    ]
